# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d1545e63d6fec0dd21f812772512e66fb7c1e56c55dbc366c227e7bbaa7ffb8fbf5f8a626b3651dfea27dff7fa9bf13ab7bcfb01d0bcbab50b056e4eadadf7e

test:
  secret_key_base: 001b9ef6e92177e605a728e580d70010e440114704b15c29f79b58796d26471d594c1662494fc08810344a46acfb4d17f1c19975ebf11c6f3b68048c89ed178a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
